[package]
name = "4x8matrix/dev-suite"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["AsynchronousMatrix"]

description = "A suite of tools for developing experiences with Roblox."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Runtime = "4x8matrix/runtime@1.0.0"
Console = "4x8matrix/console@2.1.2"
Fusion = "elttob/fusion@0.3.0"
Sift = "csqrl/sift@0.0.9"
Highlighter = "boatbomber/highlighter@0.8.3"
ClassIndex = "4x8matrix/class-index@2.0.0"