return {
	BaseBackgroundColor3 = Color3.fromRGB(32, 32, 32),
	BaseTopbarColor3 = Color3.fromRGB(27, 27, 27),
	BaseSidebarColor3 = Color3.fromRGB(22, 22, 22),

	CodeblockBackgroundColor3 = Color3.fromRGB(25, 25, 25),
	CodeblockFont = Font.fromName(Enum.Font.Gotham.Name),
	CodeblockColor3 = Color3.fromRGB(255, 255, 255),

	UIStrokeThickness = 2,

	TopbarLabelFont = Font.fromName(Enum.Font.Ubuntu.Name, Enum.FontWeight.ExtraBold),
	TopbarLabelColor3 = Color3.fromRGB(114, 114, 114),

	BaseLabelFont = Font.fromName(Enum.Font.Ubuntu.Name),
	BaseLabelColor3 = Color3.fromRGB(255, 255, 255),

	ClientColor3 = Color3.fromRGB(73, 131, 255),
	ServerColor3 = Color3.fromRGB(3, 207, 68),

	AccentColor3 = Color3.fromHex("#0b5aaf"),

	EventIconColor = Color3.fromHex("#ffff00"),
	FunctionIconColor = Color3.fromHex("#fa98fb"),
	PropertyIconColor = Color3.fromHex("#99cdff"),

	BooleanColor = Color3.fromRGB(255, 0, 0),
	NumberColor = Color3.fromRGB(255, 198, 0),
	NilColor = Color3.fromRGB(255, 198, 0),
	StringColor = Color3.fromRGB(173, 241, 149),
	EnumColor = Color3.fromRGB(0, 183, 255),
	InstanceColor = Color3.fromHex("#99cdff"),

	MiddleScrollingFrameIcon = `http://www.roblox.com/asset/?id=123032894572732`,
	TopScrollingFrameIcon = `http://www.roblox.com/asset/?id=95175423103608`,
	BottomScrollingFrameIcon = `http://www.roblox.com/asset/?id=135686768300117`,

	DropdownArrowIcon = `http://www.roblox.com/asset/?id=91919367883017`,

	MinimiseIcon = `http://www.roblox.com/asset/?id=103506812514902`,
	DevSuiteIcon = `http://www.roblox.com/asset/?id=133189525814836`,
	DashboardIcon = `http://www.roblox.com/asset/?id=125989547128015`,
	SandboxIcon = `http://www.roblox.com/asset/?id=105644859153667`,
	DatastoresIcon = `http://www.roblox.com/asset/?id=106797143762308`,
	EmbeddedIcon = `http://www.roblox.com/asset/?id=91743480578016`,
	ExplorerIcon = `http://www.roblox.com/asset/?id=116244663538470`,
	InspectorIcon =`http://www.roblox.com/asset/?id=132722856457587`,
	IntercepterIcon = `http://www.roblox.com/asset/?id=82710547910298`,
	LiveEventsIcon = `http://www.roblox.com/asset/?id=89592417172377`,
	LoggingIcon = `http://www.roblox.com/asset/?id=71965170319925`,
	StatisticsIcon = `http://www.roblox.com/asset/?id=105773589734060`,
	PerformanceIcon = `http://www.roblox.com/asset/?id=126479063941214`,

	TabIcon = `http://www.roblox.com/asset/?id=135396811830334`,

	PlayIcon = `http://www.roblox.com/asset/?id=123356194161843`,
	RestartIcon = `http://www.roblox.com/asset/?id=128203851153594`,

	EventIcon = `http://www.roblox.com/asset/?id=105282448479805`,
	FunctionIcon = `http://www.roblox.com/asset/?id=91455768893519`,
	PropertyIcon = `http://www.roblox.com/asset/?id=101344281875867`,

	PointerIcon = `http://www.roblox.com/asset/?id=73809779520162`,
	Selectioncon = `http://www.roblox.com/asset/?id=74544478147788`
}